### ISSUE TITLE
Split test from single flow into patient registration then 2 sample collection flows

### ISSUE THREAD

**Issue by pld** [onaio/rdt-standard#287]
TBD

Notes
- if we split, do not allocation 2 IDs at a time, allocate each individual on completion of form

**Comment by vincent-karuri** [comment]
Every test form is launched with two IDs (RDT and Sample ID) in case either is needed.

I do see an issue with not being able to determine if either was collected since the IDs are not deleted from the event in the case that one or both were skipped. Of course no samples or RDTs would appear at the lab with the unused IDs but we wouldn't be able to determine this from simply looking at the event.

There's also wastage of IDs in case either is not collected (the IDs will still be marked as spent).

I think @shivenbhatt1 's idea of separating the two makes sense here since we need to somehow know to generate enough IDs in advance (before launching the form).
