### ISSUE TITLE
Change ISO country code to "id" instead of "in" so we can activate translations

### ISSUE THREAD

**Issue by craigappl** [onaio/rdt-standard#301]
The two letter country code for Indonesia is "id" and transifex is throwing an error when we try to add the values-in folder. Please change the following:

1. Rename this folder to "values-id" https://github.com/onaio/rdt-standard/tree/master/rdt-open-reader/src/covidIndonesia/res/values-in
2. Change the suffix in the form name to "_id" instead of "_in" https://github.com/onaio/rdt-standard/tree/master/rdt-open-reader/src/covidIndonesia/resources
3. Update the app's logic across the board to reference the language code "id" instead of "in" in the main folder.

**Comment by vincent-karuri** [comment]
@craigappl 

This is not an app-specific implementation i.e. there is no app logic that specifically requires `in`.

Instead, this is a well-known issue where Java 8 uses old codes from the ISO 639 specification ([reference1](https://www.oracle.com/java/technologies/javase/jdk8-jre8-suported-locales.html), [reference 2](https://developer.android.com/reference/java/util/Locale#Locale(java.lang.String))).

So Android expects `in` instead of `id`.  Not sure there's a clean (non-hackish) solution for this.

**Comment by vincent-karuri** [comment]
One hack is to use a different language which we are unlikely to ever need for another project and rename the string files to use that Locale.

**Comment by vincent-karuri** [comment]
This is no longer necessary, @shivenbhatt1 was able to load the Bahasa language strings on Transifex.
