### ISSUE TITLE
Name entry fields for contact tracing are not user intuitive

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#319]
The name entry fields only show if you select the check box on the right of the following areas. Ex.

- [ ] Number of Covid-19 patients in household/compound

- [ ] Number of Covid-19 patients who are close contacts

- [ ] Number of close contacts outside patient household

**Comment by vincent-karuri** [comment]
Do you have a screenshot of this with steps of how this happened?  I'm unable to replicate.

**Comment by shivenbhatt1** [comment]
The section is under Symptoms and history, under the screen Travel and contact exposure. When identifying patient contacts with covid, the entries to input the contact information has now disappeared, which we had available before.

![image](https://user-images.githubusercontent.com/47836489/88057053-84321e80-cb2f-11ea-8f79-ba1040e1cab7.png)

**Comment by vincent-karuri** [comment]
Doesn't seem like you pressed enter or the tick icon?

**Comment by shivenbhatt1** [comment]
Ahh you're right that's it, so let's make this user-intuitive a bit because I didn't know to press the tick icon, or prevent the user from submitting the form without pressing the tick button if the number is >0. I've been submitting all the forms with >0 without any issue and without recording contacts.

**Comment by shivenbhatt1** [comment]
@rowo we need design input on the screen above that makes it more explicit that if an end-user enters a number into the columns, they must fill out contact details

**Comment by shivenbhatt1** [comment]
@rowo Could we get your input on this?

**Comment by rowo** [comment]
@shivenbhatt1 
1. So to get it right, when you say "contact", that means if you enter 2, you have to tap that checkmark which is a new screen with two string inputs? And then it brings you back to this screen with the checkmarks green?
2. If the above is correct, is there a reason/limitation why this doesn't follow the conventional workflow of like a "Other" choice where a text box shows up underneath if that is selected? 
3. By "confirm", you mean the checkbox icon needs to be tapped?

**Comment by shivenbhatt1** [comment]
@rowo If you tap the checkmark the fields for contact information display below the "2" entered.

Right now if you just enter 2 without tapping the checkbox, the user can continue through the form without adding the contact details. Maybe this might work if the form has errors for not selecting the checkmark? But I'm worried it may not be intuitive to select the checkmark.

**Comment by rowo** [comment]
@vincent-karuri @shivenbhatt1 Ok now I get it. Is there a way to:
- assume the user is done with entry if they tap off the field's input (or is that interaction not recognized)? 
- prevent a user from tapping off (i.e. maybe throwing the error and not saving the input) unless they hit the keyboard (or field input) checkbox?

Otherwise, it is a pretty unconventional interaction so I can see why it's confusing. Maybe the better option would be to use a pulldown or an [input stepper](https://www.nngroup.com/articles/input-steppers/). I think these would be better than an integer keyboard input with checkbox that is there now.

**Comment by vincent-karuri** [comment]
@rowo if by tapping off you mean navigating away from the text input, then yes, that can be tracked. It's probably more complex to prevent the user from moving on - some state will have to be maintained.

**Comment by rowo** [comment]
@vincent-karuri Great, yes I mean that. Because right now, the field registers the input if you either (1) hit the checkbox on the field or (2) hit the checkbox on the keyboard (ie. return button), but not if you just tap out and tap another field. I'm just thinking if you can tap away and it still generates the contact info fields, then we'd be okay. @shivenbhatt1 what do you think?
