### ISSUE TITLE
Display OneScan barcode capture content

### ISSUE THREAD

**Issue by shivenbhatt1** [onaio/rdt-standard#325]
Barcode information captured from OneScan be visible and confirmed to highlight the advanced features of the app and embellish the importance of the barcode.

- [x] Show the green icon for valid RDTs and red icon for unusable RDTs
- [x] Show the green icon for all samples by default
- [x] Add a back button on the result screen
- [x] Add a continue button on the result screen
- [x] Only show serial no. for samples and the 1st 7 items for RDT https://github.com/onaio/rdt-standard/issues/341#issuecomment-691111772

Mockups: https://github.com/onaio/rdt-standard/issues/341#issuecomment-689962884

**Comment by vincent-karuri** [comment]
I think this already exists?

**Comment by shivenbhatt1** [comment]
It pops up for only 2 seconds after scanning and disappears

**Comment by vincent-karuri** [comment]
The duration is configurable, that page is not really part of native forms so we should be able to navigate automatically from it without user action.

**Comment by shivenbhatt1** [comment]
We need to better format this page, the information that is extracted from the string should be visible, the user confirms and moves onto the RDT.

**Comment by shivenbhatt1** [comment]
Edit this field, use the design that Sasa provides us with the graphics

**Comment by shivenbhatt1** [comment]
Linked to https://github.com/onaio/rdt-standard/issues/341

**Comment by shivenbhatt1** [comment]
![image](https://user-images.githubusercontent.com/47836489/89652501-8f0ce300-d893-11ea-9e0c-04f2c9e19754.png)

**Comment by shivenbhatt1** [comment]
We want to add a confirm button to this screen and assets obtained from Zebra

**Comment by pld** [comment]
The confirmation screen we have here serves the same purpose as a future confirmation screen after the user selects an RDT type. We didn't discuss this, but do we also need a confirmation screen after for manual entry? Perhaps not since it won't be trigger templates, but maybe if we want a chance to check that their manual entry is the same as an RDT already in our config that they should be using instead.

In the above screen what does "Status: Ok" mean? The information it seems clear the user will want is:

- Type of product
- Type of test
- Expired or not
    - Maybe the actual expiration date, but not necessarily
- Temperature sensor triggered or not

We should also display, and require that the top 2 items above are passed. We should design the UI to look good if those are the only items that exist.

The bottom 2 items above should be displayed if they exist.

Is there value in also showing the below items?

- Product ID
- Serial number
- Lot number

That's not clear to me.

Is there anything else we'd get from the confirmation step for non-barcode that we're forgetting?

Reassigning to Shiven to post the assets from and thoughts on above.

**Comment by shivenbhatt1** [comment]
Blocked by #341

**Comment by vincent-karuri** [comment]
@shivenbhatt1 any feedback on this? Do we have a mockup for the design?

**Comment by shivenbhatt1** [comment]
@vincent-karuri roger said he'd take care of #341 by EOD Wednesday

**Comment by shivenbhatt1** [comment]
@vincent-karuri #341 now has mock images.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 https://github.com/onaio/rdt-standard/issues/325#issuecomment-670811796 this is what I was referring to. Will these screens https://github.com/onaio/rdt-standard/issues/341#issuecomment-689962884 serve this purpose?

**Comment by shivenbhatt1** [comment]
@vincent-karuri Yes, those screens work
