### ISSUE TITLE
Build the visit view 

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#379]
```
visit 1 
              ...

visit 2  
              ...
...
```

Implement a visits' view which users can navigate to from the patient profile and are presented with a list of all visits associated with a patient arranged in ascending chronological order.

@rowo may need to be consulted on whether the visit screen can be tabbed alongside this [screen](https://github.com/onaio/rdt-standard/issues/321#issuecomment-671503897) in the patient profile.

**Comment by pld** [comment]
Isn't this going to be shown in the same view as the patient info?

**Comment by vincent-karuri** [comment]
Yes, the question is whether we want to present this as a [tabbed layout](https://developer.android.com/guide/navigation/navigation-swipe-view#add_tabs_using_a_tablayout) where the visit view is a sibling to this [screen](https://github.com/onaio/rdt-standard/issues/321#issuecomment-671503897) - both within the patient profile.

**Comment by pld** [comment]
Doesn't this issue deal with the question of presenting the data within visits, https://github.com/onaio/rdt-standard/issues/380

I assumed this issue dealt with presenting the visits themselves, isn't this issue to change the profile view so that it adds a list of visit links to the bottom, not to navigate away from the profile view, https://github.com/onaio/rdt-standard/issues/321#issuecomment-670515975.

Or if not, is there a separate issue for that and how is this issue different from #380?

**Comment by vincent-karuri** [comment]
This issue deals with presenting the views themselves.

**Comment by vincent-karuri** [comment]
This [screen](https://github.com/onaio/rdt-standard/issues/321#issuecomment-670515975) is closest to what this issue describes. This is the visit view.

We decided to remove the `Visit` button from the bottom and simply list visits by date. From this visit view, we navigate to the patient history view (issue #380) by clicking on any one of the visits.

The question is how then do we access the visit view? And my suggestion is to have a tabbed layout to navigate between this [screen](https://github.com/onaio/rdt-standard/issues/321#issuecomment-671503897) and this [screen](https://github.com/onaio/rdt-standard/issues/321#issuecomment-670515975) within the patient profile.

**Comment by pld** [comment]
Got it, OK that's a good question, @rowo can you please take a look at this and make a recommendation? Not sure if we need mock-ups, it feels like we might be good there and mainly need the UX between them

**Comment by rowo** [comment]
@vincent-karuri or @shivenbhatt1 can one of you fill out [this simple information arch diagram](https://app.diagrams.net/#G1eCEd85o49mUV2qh789XxQhxxET2G-Gwj) of what's going on in https://github.com/onaio/rdt-standard/issues/321#issuecomment-671503897? Sorry, I'm not sure what's going on with all of the things in that list.. are they buttons or do they go to lists/content (just like the visits)? If they just go to more lists or information.. what's the reasoning behind putting visits in a tab?

<img width="455" alt="Screen Shot 2020-08-20 at 9 21 12 AM" src="https://user-images.githubusercontent.com/1584163/90775581-ff215d00-e2c6-11ea-93b1-e6aa977290a4.png">

**Comment by rowo** [comment]
It seems like just doing that second level as a list would fit the CHW app closest. You have a profile where you can see more detail with a tap, then a "record visit" button, then the view old visits. 

However, if like 80% of the time the user is just recording new visits, then maybe doing tabs makes sense since you can just default onto that.

**Comment by vincent-karuri** [comment]
@rowo not sure I have the picture in mind for the first part. Any quick wireframes for that?

@shivenbhatt1 for the second part, are we doing significantly more writes than reads as @rowo suggests?

**Comment by shivenbhatt1** [comment]
@vincent-karuri I predict yes, but unsure what end-users we will capture outside of the Covid-in-ANC study group. The Covid-in-ANC study is supposed to be a time-course assessment so it is expected that they will be looking back at previous visits as they record new ones.

**Comment by vincent-karuri** [comment]
@shivenbhatt1 is there a way to get this information and better refine the user flow for this?

If not, I vote on the tabbed view. I still don't know what the other option looks like.

**Comment by shivenbhatt1** [comment]
@vincent-karuri at the moment I don't have a way of getting this information. I agree with yours and Roger's instincts on the tabbed view.

**Comment by vincent-karuri** [comment]
OK, I'll implement the tabbed layout.

**Comment by rowo** [comment]
@pld @vincent-karuri I talked to @shivenbhatt1 and just wanted to point out this works differently from OpenSRP (which is a source of my confusion. Also want to cc @mberg and @hmakandi since this is kind of interesting for the Malawi issue.

In RDT, there's a series of forms that may be done (not all are required) by different users over the course of a day. The solution the team has adopted involves these forms being automatically combined into a visit at the end of the day — meaning there is no explicit "start visit" button and at the same time there is no "submit" or "save" button for the entire visit. The app user just lands on a page that has what would be equivalent to ANC Containers right off the bat. 

In other OpenSRP apps, we assume a single user with a fixed time, so there is a "start visit" button and a "save visit" button.
