### ISSUE TITLE
Not logged out after the session expired

### ISSUE THREAD

**Issue by ellyasafaa** [onaio/rdt-standard#838]
![IMG-20210303-WA0033](https://user-images.githubusercontent.com/73918009/109797060-8757c600-7c4b-11eb-95fd-18d72b2853b7.jpg)

The notification will appear in various conditions: filling in the pre-existing condition form, looking at patient history data, looking at the menu, etc. There is no specific condition that caused that and the condition will lead the user to the login page. It happened frequently and so suddenly.

Please kindly assist me with creating the issue on Github in the future since I'll be reporting via email.

**Comment by ellyasafaa** [comment]
@mwkhan1983 @vincent-karuri @syedowaisali90

**Comment by ellyasafaa** [comment]
Here is one of the examples. It is seen only a few seconds, but actually, it happened for about a minute. At that amount of time, the user is able to fill in some data, but since the session expired, it is not logged out.

https://drive.google.com/file/d/1HvAmN91ofgCQhTn85M6Bz_ibtUxT63Td/view?usp=sharing

**Comment by syedowaisali90** [comment]
Hi @ellyasafaa ,

The reason happening the logout frequently and suddenly is that because we are trying to attempt sync multiple times even it's failing. Moreover, We also trying to push the data on the server even the authorization has been failed.

To overcome this problem, I have reduced the number of retries after a failed sync to 1 from the current 3 and also stop to pushing the data on the server if the user has not authorized it and log out the user instantly.

**The caveat here:** We will logout the user only when the sync failed due to the user verification, and it will be performed by the system or user.

**Comment by vincent-karuri** [comment]
@syedowaisali90, As discussed, we don't need to reduce the retries with the configuration change.

**Comment by vincent-karuri** [comment]
We also won't be attempting sync when authorization fails, so it should logout the user faster

**Comment by mwkhan1983** [comment]
@syedowaisali90 I have tested the session expiry issue. It seems to work fine in the following case:

Case #1
1. Login 
2. Let the app sync
3. Leave the app in the background
4. Resume using the app after timeout (2 minutes in this case)
5.  Notification appears and then user is logged out with appropriate message
6. Log back in. User successfully logs in. Token refreshed. Data synced

However, I found an issue in the following case:
Case # 2
1. Login
2. Let the app sync
3. Log out
4. Come back to the app after timeout (2 minutes in this case)
5. Log back in. Notification appears and user is logged out and the message shown. Now on login screen, message appears again. 

This is not the desired behavior. It should have refreshed the token similar to case # 1 above.
