### ISSUE TITLE
Add login screen

### ISSUE THREAD

**Issue by vincent-karuri** [onaio/rdt-standard#85]

**Comment by vincent-karuri** [comment]
@rowo please also provide a simple logo or design for the login screen

It's can follow the standard opensrp login feel/look.

**Comment by rowo** [comment]
@vincent-karuri What are the requirements around this logo?

**Comment by vincent-karuri** [comment]
I don't believe there's any hard requirements but @pld suggested that it could contain the Ona logo somewhere.

**Comment by rowo** [comment]
@pld @shivenbhatt1 any requirements in this login page? We don't actually have a login page that just has an OpenSRP logo since no apps have been called "OpenSRP" yet. They are just "Powered by OpenSRP"

**Comment by pld** [comment]
Yea, this is a bit different, since it's our deployment we can dictate what's on it. There are no firm requirements, so we should do what ever is strategically best for us to get more work/clients/partners, be seen as leaders/innovators.

We could call it an "Ona" deployment that's "powered by OpenSRP".

We could also add "RDT Open Guidelines" we that have any logos for this or a short name, I've called in RapidOS when it used to be called Open Standards but I don't do that anymore. We could it RapidOG or RDT OG or none of that and keep the full name. There's also no logo for this yet.

Also useful background that we changed the communication about the project from "Open Standards RDTs" to "Open Guidelines RDTs" based on feedback from manufacturers that they didn't want to be tied to "standards" and they'd be less likely to participate if it was called that.

**Comment by rowo** [comment]
I don't think I have time to make a logo yet, so for now can we just use text with that acknowledgement text you described? We can keep this issue open until we do have a logo.

![Log in RDT](https://user-images.githubusercontent.com/1584163/61405669-5ffe8a80-a8a8-11e9-8901-17c03ca02910.png)

**Comment by pld** [comment]
What do you think about an Ona and OpenSRP logo on this screen?

**Comment by rowo** [comment]
I don't think you need to always put a logo when mentioning the organizations, but we can. It is just busy with the app not having a logo.

For the app itself, I think of the guidelines as separate from this app. The app itself probably needs a name that can fit on one line and sounds more like an app name. Anyone want to take a stab at thinking of a list of potentials to add to what Peter has? 

https://hackernoon.com/a-quick-7-step-guide-for-naming-your-next-app-or-startup-481c260528da

RDT Open Guidelines
RapidOG 
RDT OG

**Comment by vincent-karuri** [comment]
I'll go ahead and implement the screen as is, even as the discussion continues.

Since the login logic is already in place.

**Comment by pld** [comment]
we're naming the app `RDT Open Reader` for now

**Comment by pld** [comment]
@rowo should we use the same logo as we had on the printed bag for this?

**Comment by rowo** [comment]
@pld Sure thing. And using "RDT Open Reader"?

**Comment by pld** [comment]
Yea, what's in the thread above

**Comment by rowo** [comment]
@vincent-karuri 

Here's the logo and a new screen mockup:

![Log in RDT](https://user-images.githubusercontent.com/1584163/62966885-f2297e00-bdd5-11e9-9469-10920e476deb.png)
![rdt-icon](https://user-images.githubusercontent.com/1584163/62966886-f2297e00-bdd5-11e9-924d-2027a4f66095.png)

**Comment by vincent-karuri** [comment]
Thanks @rowo
